const Map<String, String> en = {
  // App branding
  'app_name': "Fin'nalyze",
  'app_tagline':
      'Upload your financial documents,\nlet your AI assistant analyze and advise.',
  'login_feature_upload': 'Upload',
  'login_feature_ai': 'AI insights',
  'login_feature_card_summary': 'Card summaries',

  // Login
  'login_welcome_title': 'Welcome',
  'login_welcome_subtitle':
      'Continue your financial analysis from where you left off.',
  'email_label': 'Email Address',
  'email_hint': 'example@company.com',
  'password_label': 'Password',
  'forgot_password': 'Forgot Password',
  'remember_me': 'Remember me',
  'login_button': 'Sign In',
  'or_divider': 'OR',
  'sign_in_with_google': 'Sign in with Google',
  'no_account': "Don't have an account?",
  'register_link': 'Sign Up',

  // Validation
  'email_empty': 'Email is required',
  'email_invalid': 'Enter a valid email address',
  'password_empty': 'Password is required',
  'password_min_length': 'Password must be at least 6 characters',

  // Auth feedback
  'login_success': 'Signed in successfully',
  'login_error': 'Could not sign in. Please try again.',
  'google_sign_in_coming_soon': 'Google sign-in coming soon',
  'forgot_password_coming_soon': 'Password reset coming soon',

  // Home
  'home_greeting': 'Hello, @name 👋',
  'home_greeting_subtitle':
      'Your financial situation looks quite stable today.',
  'home_greeting_tagline':
      'Track your financial documents easily and get insights from your assistant.',
  'doc_detail_category_tabs_title': 'Spending by category',
  'doc_detail_category_expense_summary':
      '@category: @count transactions · @amount',
  'doc_detail_category_expenses_empty':
      'No expenses in this category.',
  'home_credit_cards_title': 'MY CREDIT CARD STATEMENTS',
  'home_credit_cards_empty':
      'No credit card statements uploaded yet. Upload a PDF to see current debt and payment due date.',
  'home_credit_cards_upload': 'Upload Statement',
  'home_credit_current_debt': 'Current Debt',
  'home_credit_payment_due': 'Payment Due Date',
  'home_credit_minimum_payment': 'Minimum Payment',
  'home_credit_last_payment': 'Last Payment',
  'home_credit_statement_period': 'Statement Period',
  'home_credit_card_limit': 'Card Limit',
  'home_credit_available_limit': 'Available Limit',
  'home_ai_ready_title': 'AI Analysis Ready',
  'home_ai_ready_subtitle':
      'Analyses for your recently uploaded documents are ready. Tap the title for details.',
  'home_ai_ready_subtitle_count':
      'Analyses for your last @count document(s) are ready. Tap the title for details.',
  'home_ai_empty_subtitle':
      'Upload your financial documents to see AI analysis and recommendations here.',
  'home_ai_upload_new': 'Upload a document for new analysis',
  'home_ai_view_analyses': 'View analyses',
  'home_insights_title': 'Overview',
  'home_insights_doc_count': 'docs',
  'home_insights_top_category': 'Top spend',
  'home_insights_total_debt': 'Total CC Debt',
  'home_insights_total_expense': 'Total Expense',
  'home_cta_subtitle':
      'Upload your first statement,\nlet your AI assistant analyze it.',
  'home_view_reports': 'View Reports',
  'home_view_analyses': 'View Analyses',
  'home_notifications_title': 'Notifications',
  'home_notifications_empty': 'No alerts right now.',
  'home_notifications_payment_due':
      '@title · Payment due @date (@days days left)',
  'home_notifications_payment_due_today':
      '@title · Payment due today (@date)',
  'home_notifications_payment_overdue':
      '@title · Payment due date passed (@date)',
  'home_my_documents': 'My Documents',
  'home_documents_empty': 'No documents yet. Upload a statement to get started.',
  'home_doc_selector_title': 'My Documents',
  'home_doc_summary_title': 'Document Summary',
  'home_doc_switch_in_analysis':
      'Switch documents in the Analysis tab.',
  'home_doc_limit_label': 'Card Limit',
  'home_doc_limit_used': 'Used',
  'home_doc_limit_available': 'Available',
  'home_doc_vs_last_month': 'vs last month',
  'home_doc_comparison_more': '@pct% more spent',
  'home_doc_comparison_less': '@pct% less spent',
  'home_doc_daily_chart_title': 'Daily Spending',
  'home_doc_chart_peak': 'Peak day',
  'home_doc_btn_view': 'View All Analyses',
  'home_doc_btn_upload': 'Upload New Document',
  'home_spending_trend_title': 'SPENDING TREND',
  'home_spending_trend_period': 'Last 7 Days',
  'home_spending_trend_full_period': 'Statement period',
  'home_spending_trend_period_weekly': 'Weekly summary',
  'home_spending_trend_period_monthly': 'Monthly summary',
  'home_chart_touch_hint': 'Tap for details',
  'home_chart_tooltip_peak': 'Peak day',
  'home_total_spending_label': 'Total Spending',
  'home_ai_suggestion_label': 'AI INSIGHT',
  'home_ai_insight_empty':
      'Upload a statement to see period summary and AI tips here.',
  'home_ai_insight_no_compare':
      'No prior period document — upload an earlier statement for the same card.',
  'home_ai_insight_stable':
      'Your spending mix is similar to the previous period.',
  'home_ai_insight_total_more':
      'Total spending is @pct% higher than last month.',
  'home_ai_insight_total_less':
      'Total spending is @pct% lower than last month.',
  'home_ai_insight_category_more':
      '@category spending is @pct% higher than last month.',
  'home_ai_insight_category_less':
      '@category spending is @pct% lower than last month.',
  'home_open_analysis_tab': 'Open in Analysis',
  'home_open_full_detail': 'Full detail',
  'home_summary_preview': 'AI Summary',
  'doc_delete_title': 'Delete document',
  'doc_delete_confirm': 'Are you sure you want to delete @title?',
  'doc_delete_cancel': 'Cancel',
  'doc_delete_confirm_action': 'Delete',
  'doc_delete_success': 'Document deleted.',
  'home_recent_documents': 'Recent Documents',
  'home_see_all': 'See All',
  'home_ai_summary_badge': 'AI Summary',
  'nav_home': 'Home',
  'nav_documents': 'Documents',
  'nav_analysis': 'Analysis',
  'nav_settings': 'Settings',
  'settings_title': 'Settings',
  'settings_section_preferences': 'PREFERENCES',
  'settings_section_account': 'ACCOUNT',
  'settings_language': 'Language',
  'settings_language_tr': 'Türkçe',
  'settings_language_en': 'English',
  'settings_about': 'About App',
  'settings_about_text':
      "Fin'nalyze v1.0.0 · AI-powered financial document analysis · Hack3athon'26",
  'settings_logout': 'Log Out',
  'settings_logout_title': 'Log Out',
  'settings_logout_confirm': 'Are you sure you want to log out?',
  'settings_logout_action': 'Log Out',
  'home_tab_documents_hint': 'Manage all your documents here.',
  'home_tab_analysis_hint':
      'Upload a document or tap a past document to view its AI analysis.',
  'home_notifications_coming_soon': 'Notifications coming soon',
  'home_analysis_for_document': '@title — AI Analysis',
  'home_analysis_coming_detail':
      'AI analysis, summary, and recommendations for this document will appear here soon.',

  // Document upload
  'upload_title': 'Upload Document',
  'upload_subtitle': 'Prepare your financial documents for AI analysis.',
  'upload_step_choose': 'Choose',
  'upload_step_review': 'Review',
  'upload_step_analyze': 'Analyze',
  'upload_drop_title': 'Drag or select your document here',
  'upload_drop_analysis_hint':
      'Select a file or upload a photo to see your document analysis.',
  'upload_drop_subtitle': 'PDF format only (Maximum @max MB)',
  'upload_tap_pdf': 'Tap to Upload PDF',
  'upload_max_size': 'Max file size: @max MB',
  'upload_select_file': 'Select File',
  'upload_scan': 'Scan',
  'upload_scan_sheet_title': 'Add document with a photo',
  'upload_browse': 'Browse',
  'upload_source_sheet_title': 'How would you like to add a document?',
  'upload_source_browse': 'Browse Files (PDF)',
  'upload_source_scan_camera': 'Take a Photo',
  'upload_source_scan_gallery': 'Choose Photo from Gallery',
  'upload_ai_section_title': 'AI Analysis',
  'upload_ai_feature_1': 'Balance sheet and income statement detection',
  'upload_ai_feature_2': 'Automatic anomaly scanning',
  'upload_ai_feature_3': 'Risk scoring and trend analysis',
  'upload_ai_feature_4': 'Market-aware recommendations',
  'upload_recent_scanned': 'Recently Scanned',
  'upload_view_all': 'VIEW ALL',
  'upload_view_less': 'VIEW LESS',
  'upload_view_insights': 'View analysis',
  'upload_history_empty': 'No uploaded documents yet.',
  'upload_today': 'Today',
  'upload_name_sheet_title': 'Analysis Complete',
  'upload_name_sheet_subtitle':
      'You can customize the document name and period.',
  'upload_name_sheet_label_title': 'Document Name',
  'upload_name_sheet_hint_title': 'e.g. Maximum Genç Visa',
  'upload_name_sheet_label_period': 'Period',
  'upload_name_sheet_hint_period': 'Jan 2026 – Feb 2026',
  'upload_name_sheet_skip': 'Skip',
  'upload_name_sheet_save': 'Save & Continue',
  'doc_edit_title': 'Edit',
  'doc_edit_sheet_title': 'Edit Document',
  'upload_status_analyzing': 'Analyzing...',
  'upload_status_complete': 'Complete',
  'upload_analyzing_title': 'Your document is being analyzed...',
  'upload_analyzing_subtitle': 'Please wait',
  'upload_analyzing_header': 'Analyzing',
  'upload_status_upload_done': 'Upload Completed',
  'upload_status_parsing': 'Parsing Data',
  'upload_powered_by': 'POWERED BY FIN\'NALYZE AI ENGINE',
  'upload_file_too_large': 'File exceeds the @max MB limit',
  'upload_invalid_pdf': 'Please select a valid PDF file.',
  'upload_not_statement':
      'This file does not look like a bank statement or card summary. Upload a statement PDF.',
  'upload_pick_cancelled': 'File selection cancelled',
  'upload_pick_error': 'Could not select file. Please try again.',
  'upload_pdf_only_for_analysis': 'Please select a PDF file for AI analysis.',
  'upload_duplicate_file':
      'This PDF is already uploaded. Open it from Documents or Analysis.',
  'upload_status_error': 'Analysis failed',
  'upload_camera_error': 'Could not open camera',
  'upload_gallery_error': 'Could not open gallery',
  'error_gemini_parse': 'Could not analyze document. Try a different PDF.',
  'error_gemini_unavailable':
      'AI service is busy. Please try again in a few minutes.',
  'error_gemini_empty': 'AI returned no response. Please upload the PDF again.',
  'error_gemini_blocked': 'Document was blocked by safety filters. Try another PDF.',
  'error_gemini_quota': 'Daily AI limit reached. Try again tomorrow.',
  'error_gemini_api_key': 'Invalid Gemini API key. Check your .env file.',
  'error_gemini_region': 'Gemini API is not available in your region.',

  // Document detail
  'doc_detail_untitled': 'Document Detail',
  'doc_detail_summary_title': 'Summary',
  'doc_detail_summary_empty': 'No summary was generated for this document.',
  'doc_detail_financial_title': 'Financial Summary',
  'doc_detail_total_income': 'Total Income',
  'doc_detail_total_expense': 'Total Expense',
  'doc_detail_closing_balance': 'Closing Balance',
  'doc_detail_closing': 'Closing',
  'doc_detail_category_all': 'All',
  'doc_detail_category_tx_count': '@count transactions',
  'doc_detail_category_summary': '@count transactions · @amount spent',
  'expense_category_market': 'Groceries',
  'expense_category_food': 'Food & Dining',
  'expense_category_clothing': 'Clothing',
  'expense_category_transport': 'Transport',
  'expense_category_bills': 'Bills',
  'expense_category_health': 'Health',
  'expense_category_entertainment': 'Entertainment',
  'expense_category_education': 'Education',
  'expense_category_subscription': 'Subscriptions',
  'expense_category_transfer': 'Transfer',
  'expense_category_other': 'Other',
  'doc_detail_expense_distribution': 'Spending Breakdown',
  'doc_detail_chart_empty': 'No expense data available.',
  'doc_ai_section_summary': 'Document Summary',
  'doc_ai_section_recommendations': 'Personal Recommendations',
  'doc_ai_summary_period': 'Statement Period',
  'doc_ai_summary_last_payment': 'Last Payment',
  'doc_ai_summary_next_payment': 'Next Payment Due',
  'doc_ai_summary_highlights': 'Highlights',
  'doc_detail_ai_analysis': '✨ AI Analysis',
  'doc_detail_insights_title': 'Key Insights',
  'doc_detail_top_expense': 'Largest Expense',
  'doc_detail_total_transactions': 'Total Transactions',
  'doc_detail_savings_potential': 'Savings Potential',
  'doc_detail_no_expense': 'No expense transactions',
  'doc_detail_tab_transactions': 'Transactions',
  'doc_detail_tab_analysis': 'Analysis',
  'doc_detail_tab_recommendations': 'AI Tips',
  'doc_tab_transactions': 'Transactions',
  'doc_tab_analysis': 'Analysis',
  'doc_tab_summary': 'Summary',
  'doc_tab_ai': 'AI',
  'doc_tab_installments': 'Installments',
  'doc_installments_empty':
      'No installment transactions in this document.',
  'doc_installments_monthly': 'This Month',
  'doc_installments_remaining_total': 'Remaining Total',
  'doc_installments_count': 'Items',
  'doc_installments_this_month': 'This month',
  'doc_installments_paid': 'Paid',
  'doc_installments_left_count': 'Left',
  'doc_installments_installment': 'installment',
  'doc_installments_remaining_amount': 'Remaining',
  'doc_detail_gross_expense': 'Gross Expense',
  'doc_detail_min_payment': 'Min. Payment',
  'doc_detail_payment_due': 'Payment Due',
  'doc_grouped_view': 'Grouped',
  'doc_list_view': 'List',
  'doc_carryover_label': 'Previous Period Credit',
  'doc_net_debt_label': 'Net Period Debt',
  'doc_debt_calc_title': '💳 Debt Payoff Plan',
  'doc_debt_calc_current_debt': 'Current Debt',
  'doc_debt_calc_min_payment': 'Minimum Payment',
  'doc_debt_calc_min_scenario': 'Paying minimum only: @months months',
  'doc_debt_calc_min_detail': 'Total paid @total · Interest cost @interest',
  'doc_debt_calc_full_scenario': 'Pay full balance now',
  'doc_debt_calc_full_detail': 'Save @savings in interest 🎉',
  'doc_installments_title': 'Ongoing Installments',
  'doc_future_period_title': 'Next Period',
  'doc_next_statement': 'Next Statement Date',
  'doc_next_payment_due': 'Next Payment Due',
  'doc_detail_recurring_title': 'Recurring Payments',
  'doc_detail_recurring_empty': 'No recurring expenses detected.',
  'doc_detail_recurring_count': '@count times',
  'doc_detail_ai_rec_idle_title': 'Personal AI recommendations',
  'doc_detail_ai_rec_fetch': 'Get Recommendations',
  'doc_detail_ai_rec_loading': 'AI is analyzing...',
  'doc_detail_ai_rec_error':
      'Could not load recommendations. Check your connection and try again.',
  'doc_detail_ai_rec_retry': 'Retry',
  'doc_detail_transactions_title': 'Transactions',
  'doc_detail_transactions_by_category': 'Expenses by Category',
  'doc_detail_transactions_empty': 'No transactions found.',
  'doc_detail_recommendations_empty': 'No recommendations yet',
  'doc_rec_priority_high': 'High',
  'doc_rec_priority_medium': 'Medium',
  'doc_rec_priority_low': 'Low',
  'doc_rec_overspend_title': 'Spending exceeds income',
  'doc_rec_overspend_body':
      'Expenses are higher than income this period. Review discretionary spending.',
  'doc_rec_top_expense_title': 'Largest expense: @merchant',
  'doc_rec_top_expense_body':
      'This @amount expense had the biggest impact on your budget.',
  'doc_rec_savings_title': 'Room to save',
  'doc_rec_savings_body':
      'Your income exceeds expenses. Consider directing the surplus to savings or debt.',
  'doc_rec_summary_title': 'AI assessment',
  'doc_detail_not_found':
      'Document analysis not found. Please upload the PDF again.',
  'doc_preview_unavailable':
      'PDF preview is unavailable. Please upload the document again.',
  'doc_analysis_incomplete':
      'AI analysis for this document is missing or failed. Re-analyze if the PDF is still saved.',
  'doc_reanalyze_action': 'Re-analyze',
  'doc_reanalyze_success_title': 'Analysis complete',
  'doc_reanalyze_success': 'Document data has been updated.',

  // Documents tab
  'documents_tab_title': 'My Documents',
  'documents_tab_subtitle':
      'Upload PDF statements and manage your upload history.',

  // Analysis tab
  'analysis_select_document':
      'Tap a document to choose viewing or AI analysis.',
  'analysis_empty': 'No documents to analyze yet. Upload a PDF first.',
  'analysis_action_title': 'What would you like to do?',
  'analysis_open_ai': 'AI Analysis',
  'analysis_open_pdf': 'View Document',

  // Aggregate
  'aggregate_title': 'All Periods',
  'aggregate_grand_total': 'Overview',
  'aggregate_total_expense': 'Total Expense',
  'aggregate_total_income': 'Total Income',
  'aggregate_total_debt': 'Total CC Debt',
  'aggregate_doc_count': 'Docs',
  'aggregate_monthly_chart': 'Monthly Spending Trend',
  'aggregate_top_categories': 'Category Breakdown (All Periods)',
  'aggregate_ai_insight': 'AI Trend Analysis',
  'aggregate_ai_load': 'Load Trend Analysis',
  'aggregate_ai_retry': 'Retry',
  'aggregate_empty':
      'No documents uploaded yet.\nUpload a statement to see monthly trends.',
};
