const Map<String, String> tr = {
  // App branding
  'app_name': "Fin'nalyze",
  'app_tagline':
      'Finansal belgelerinizi yükleyin,\nasistanınız analiz etsin ve önerilerini sunsun.',
  'login_feature_upload': 'Belge yükle',
  'login_feature_ai': 'AI analiz',
  'login_feature_card_summary': 'Kart özetleri',

  // Login
  'login_welcome_title': 'Hoş Geldiniz',
  'login_welcome_subtitle':
      'Finansal analizlerinize kaldığınız yerden devam edin.',
  'email_label': 'E-posta Adresi',
  'email_hint': 'ornek@sirket.com',
  'password_label': 'Şifre',
  'forgot_password': 'Şifremi Unuttum',
  'remember_me': 'Beni hatırla',
  'login_button': 'Giriş Yap',
  'or_divider': 'VEYA',
  'sign_in_with_google': 'Google ile Giriş Yap',
  'no_account': 'Hesabınız yok mu?',
  'register_link': 'Kayıt Ol',

  // Validation
  'email_empty': 'E-posta adresi gerekli',
  'email_invalid': 'Geçerli bir e-posta adresi girin',
  'password_empty': 'Şifre gerekli',
  'password_min_length': 'Şifre en az 6 karakter olmalı',

  // Auth feedback
  'login_success': 'Giriş başarılı',
  'login_error': 'Giriş yapılamadı. Lütfen tekrar deneyin.',
  'google_sign_in_coming_soon': 'Google ile giriş yakında aktif olacak',
  'forgot_password_coming_soon': 'Şifre sıfırlama yakında aktif olacak',

  // Home
  'home_greeting': 'Merhaba, @name 👋',
  'home_greeting_subtitle':
      'Finansal durumun bugün oldukça stabil görünüyor.',
  'home_greeting_tagline':
      'Finansal belgelerinizi kolayca takip edin, asistanınızın önerilerini alın.',
  'doc_detail_category_tabs_title': 'Kategoriye göre harcamalar',
  'doc_detail_category_expense_summary':
      '@category: @count işlem · @amount',
  'doc_detail_category_expenses_empty':
      'Bu kategoride harcama bulunamadı.',
  'home_credit_cards_title': 'KREDİ KARTI EKSTRELERİM',
  'home_credit_cards_empty':
      'Henüz kredi kartı ekstresi yüklenmedi. PDF yükleyerek güncel borç ve son ödeme tarihini görüntüleyin.',
  'home_credit_cards_upload': 'Ekstre Yükle',
  'home_credit_current_debt': 'Güncel Borç',
  'home_credit_payment_due': 'Son Ödeme Tarihi',
  'home_credit_minimum_payment': 'Asgari Ödeme',
  'home_credit_last_payment': 'Son Yapılan Ödeme',
  'home_credit_statement_period': 'Ekstre Dönemi',
  'home_credit_card_limit': 'Kart Limiti',
  'home_credit_available_limit': 'Kullanılabilir Limit',
  'home_ai_ready_title': 'AI Analiz Hazır',
  'home_ai_ready_subtitle':
      'Son yüklediğiniz belgelerin analizleri hazır. Detaylar için başlığa dokunun.',
  'home_ai_ready_subtitle_count':
      'Son yüklediğiniz @count belgenin analizi hazır. Detaylar için başlığa dokunun.',
  'home_ai_empty_subtitle':
      'Finansal belgelerinizi yükleyin; AI analizi ve öneriler burada görünsün.',
  'home_ai_upload_new': 'Yeni analiz için belge yükle',
  'home_ai_view_analyses': 'Analizleri görüntüle',
  'home_insights_title': 'Genel Özet',
  'home_insights_doc_count': 'belge',
  'home_insights_top_category': 'En yüksek',
  'home_insights_total_debt': 'Toplam KK Borcu',
  'home_insights_total_expense': 'Toplam Harcama',
  'home_cta_subtitle':
      'İlk ekstrenizi yükleyin,\nAI asistanınız analiz etsin.',
  'home_view_reports': 'Raporları Görüntüle',
  'home_view_analyses': 'Analizleri Görüntüle',
  'home_notifications_title': 'Bildirimler',
  'home_notifications_empty': 'Şu an için uyarı bulunmuyor.',
  'home_notifications_payment_due':
      '@title · Son ödeme @date (@days gün kaldı)',
  'home_notifications_payment_due_today':
      '@title · Son ödeme bugün (@date)',
  'home_notifications_payment_overdue':
      '@title · Son ödeme tarihi geçti (@date)',
  'home_my_documents': 'Belgelerim',
  'home_documents_empty': 'Henüz belge yok. Ekstre yükleyerek başlayın.',
  'home_doc_selector_title': 'Belgelerim',
  'home_doc_summary_title': 'Belge Özeti',
  'home_doc_switch_in_analysis':
      'Diğer belgeler için Analiz sekmesine geçin.',
  'home_doc_limit_label': 'Kart Limiti',
  'home_doc_limit_used': 'Kullanılan',
  'home_doc_limit_available': 'Kalan',
  'home_doc_vs_last_month': 'Geçen aya göre',
  'home_doc_comparison_more': '%@pct fazla harcandı',
  'home_doc_comparison_less': '%@pct daha az harcandı',
  'home_doc_daily_chart_title': 'Günlük Harcamalar',
  'home_doc_chart_peak': 'En yüksek gün',
  'home_doc_btn_view': 'Analizleri Görüntüle',
  'home_doc_btn_upload': 'Yeni Belge Yükle',
  'home_spending_trend_title': 'HARCAMA TRENDİ',
  'home_spending_trend_period': 'Son 7 Gün',
  'home_spending_trend_full_period': 'Ekstre dönemi',
  'home_spending_trend_period_weekly': 'Haftalık özet',
  'home_spending_trend_period_monthly': 'Aylık özet',
  'home_chart_touch_hint': 'Detay için dokunun',
  'home_chart_tooltip_peak': 'En yüksek gün',
  'home_total_spending_label': 'Toplam Harcama',
  'home_ai_suggestion_label': 'AI ÖNERİSİ',
  'home_ai_insight_empty':
      'Belge yükleyin; dönem özeti ve AI önerileri burada görünsün.',
  'home_ai_insight_no_compare':
      'Önceki dönem belgesi yok; karşılaştırma için aynı kartın geçmiş ekstresini yükleyin.',
  'home_ai_insight_stable': 'Bu dönem harcama dağılımınız önceki döneme yakın.',
  'home_ai_insight_total_more':
      'Geçen aya göre toplam harcamanız %@pct arttı.',
  'home_ai_insight_total_less':
      'Geçen aya göre toplam harcamanız %@pct azaldı.',
  'home_ai_insight_category_more':
      'Geçen aya göre @category harcamalarınız %@pct arttı.',
  'home_ai_insight_category_less':
      'Geçen aya göre @category harcamalarınız %@pct azaldı.',
  'home_open_analysis_tab': 'Analiz sekmesinde aç',
  'home_open_full_detail': 'Detaylı görünüm',
  'home_summary_preview': 'AI Özeti',
  'doc_delete_title': 'Belgeyi sil',
  'doc_delete_confirm': '@title belgesini silmek istediğinize emin misiniz?',
  'doc_delete_cancel': 'Vazgeç',
  'doc_delete_confirm_action': 'Sil',
  'doc_delete_success': 'Belge silindi.',
  'home_recent_documents': 'Son Belgeler',
  'home_see_all': 'Tümünü Gör',
  'home_ai_summary_badge': 'AI Özet',
  'nav_home': 'Ana Sayfa',
  'nav_documents': 'Belgeler',
  'nav_analysis': 'Analiz',
  'nav_settings': 'Ayarlar',
  'settings_title': 'Ayarlar',
  'settings_section_preferences': 'TERCİHLER',
  'settings_section_account': 'HESAP',
  'settings_language': 'Dil',
  'settings_language_tr': 'Türkçe',
  'settings_language_en': 'English',
  'settings_about': 'Uygulama Hakkında',
  'settings_about_text':
      "Fin'nalyze v1.0.0 · AI destekli finansal belge analizi · Hack3athon'26",
  'settings_logout': 'Çıkış Yap',
  'settings_logout_title': 'Çıkış Yap',
  'settings_logout_confirm':
      'Hesabınızdan çıkış yapmak istediğinize emin misiniz?',
  'settings_logout_action': 'Çıkış Yap',
  'home_tab_documents_hint': 'Tüm belgelerinizi buradan yönetin.',
  'home_tab_analysis_hint':
      'Belge yükleyin veya geçmiş belgelerden birine dokunarak AI analizini görün.',
  'home_notifications_coming_soon': 'Bildirimler yakında aktif olacak',
  'home_analysis_for_document': '@title — AI Analizi',
  'home_analysis_coming_detail':
      'Bu belgeye özel AI analizi, özet ve öneriler yakında burada görünecek.',

  // Document upload
  'upload_title': 'Doküman Yükle',
  'upload_subtitle': 'Finansal belgelerinizi AI analizi için hazırlayın.',
  'upload_step_choose': 'Seç',
  'upload_step_review': 'İncele',
  'upload_step_analyze': 'Analiz',
  'upload_drop_title': 'Belgenizi buraya sürükleyin veya seçin',
  'upload_drop_analysis_hint':
      'Belgenizin analizini görmek için dosya seçin veya fotoğraf yükleyin.',
  'upload_drop_subtitle': 'Yalnızca PDF formatı (Maksimum @max MB)',
  'upload_tap_pdf': 'PDF Yüklemek İçin Dokunun',
  'upload_max_size': 'Maksimum dosya boyutu: @max MB',
  'upload_select_file': 'Dosya Seç',
  'upload_scan': 'Tara',
  'upload_scan_sheet_title': 'Fotoğraf ile belge ekle',
  'upload_browse': 'Dosya Seç',
  'upload_source_sheet_title': 'Belge nasıl eklensin?',
  'upload_source_browse': 'Dosya Seç (PDF)',
  'upload_source_scan_camera': 'Fotoğraf Çek',
  'upload_source_scan_gallery': 'Galeriden Fotoğraf Seç',
  'upload_ai_section_title': 'AI Analizi',
  'upload_ai_feature_1': 'Bilanço ve gelir tabloları tespiti',
  'upload_ai_feature_2': 'Otomatik anormallik taraması',
  'upload_ai_feature_3': 'Risk puanlaması ve trend analizi',
  'upload_ai_feature_4': 'Piyasa verisiyle bağlamlı öneriler',
  'upload_recent_scanned': 'Son Tarananlar',
  'upload_view_all': 'TÜMÜNÜ GÖR',
  'upload_view_less': 'DAHA AZ',
  'upload_view_insights': 'Analizi görüntüle',
  'upload_history_empty': 'Henüz yüklenmiş belge yok.',
  'upload_today': 'Bugün',
  'upload_name_sheet_title': 'Analiz Tamamlandı',
  'upload_name_sheet_subtitle':
      'Belge adını ve dönemini özelleştirebilirsin.',
  'upload_name_sheet_label_title': 'Belge Adı',
  'upload_name_sheet_hint_title': 'Örn: Maximum Genç Visa',
  'upload_name_sheet_label_period': 'Dönem',
  'upload_name_sheet_hint_period': 'Oca 2026 – Şub 2026',
  'upload_name_sheet_skip': 'Atla',
  'upload_name_sheet_save': 'Kaydet ve Devam Et',
  'doc_edit_title': 'Düzenle',
  'doc_edit_sheet_title': 'Belgeyi Düzenle',
  'upload_status_analyzing': 'Analiz ediliyor...',
  'upload_status_complete': 'Tamamlandı',
  'upload_analyzing_title': 'Belgeniz analiz ediliyor...',
  'upload_analyzing_subtitle': 'Lütfen bekleyin',
  'upload_analyzing_header': 'Analiz Ediliyor',
  'upload_status_upload_done': 'Yükleme Tamamlandı',
  'upload_status_parsing': 'Veri Ayrıştırılıyor',
  'upload_powered_by': "FIN'NALYZE AI ENGINE İLE DESTEKLENİR",
  'upload_file_too_large': 'Dosya @max MB sınırını aşıyor',
  'upload_invalid_pdf': 'Geçerli bir PDF dosyası seçin.',
  'upload_not_statement':
      'Bu dosya banka ekstresi veya kart özeti gibi görünmüyor. Ekstre PDF\'i yükleyin.',
  'upload_pick_cancelled': 'Dosya seçimi iptal edildi',
  'upload_pick_error': 'Dosya seçilemedi. Tekrar deneyin.',
  'upload_pdf_only_for_analysis': 'AI analizi için lütfen PDF dosyası seçin.',
  'upload_duplicate_file':
      'Bu PDF zaten yüklendi. Belgeler veya Analiz sekmesinden açabilirsiniz.',
  'upload_status_error': 'Analiz başarısız',
  'upload_camera_error': 'Kamera açılamadı',
  'upload_gallery_error': 'Galeri açılamadı',
  'error_gemini_parse': 'Belge analiz edilemedi. Farklı bir PDF dene.',
  'error_gemini_unavailable':
      'AI servisi şu an yoğun. Birkaç dakika sonra tekrar dene.',
  'error_gemini_empty': 'AI yanıt vermedi. PDF\'i tekrar yükleyin.',
  'error_gemini_blocked': 'Belge güvenlik filtresine takıldı. Farklı bir PDF deneyin.',
  'error_gemini_quota': 'Günlük AI limiti aşıldı. Yarın tekrar dene.',
  'error_gemini_api_key': 'Gemini API anahtarı geçersiz. .env dosyanı kontrol et.',
  'error_gemini_region': 'Gemini API bu bölgede kullanılamıyor.',

  // Document detail
  'doc_detail_untitled': 'Belge Detayı',
  'doc_detail_summary_title': 'Özet',
  'doc_detail_summary_empty': 'Bu belge için özet oluşturulamadı.',
  'doc_detail_financial_title': 'Finansal Özet',
  'doc_detail_total_income': 'Toplam Gelir',
  'doc_detail_total_expense': 'Toplam Gider',
  'doc_detail_closing_balance': 'Kapanış Bakiyesi',
  'doc_detail_closing': 'Kapanış',
  'doc_detail_category_all': 'Tümü',
  'doc_detail_category_tx_count': '@count işlem',
  'doc_detail_category_summary': '@count işlem · @amount harcama',
  'expense_category_market': 'Market',
  'expense_category_food': 'Yeme-İçme',
  'expense_category_clothing': 'Giyim',
  'expense_category_transport': 'Ulaşım',
  'expense_category_bills': 'Faturalar',
  'expense_category_health': 'Sağlık',
  'expense_category_entertainment': 'Eğlence',
  'expense_category_education': 'Eğitim',
  'expense_category_subscription': 'Abonelik',
  'expense_category_transfer': 'Transfer',
  'expense_category_other': 'Diğer',
  'doc_detail_expense_distribution': 'Harcama Dağılımı',
  'doc_detail_chart_empty': 'Gider verisi bulunamadı.',
  'doc_ai_section_summary': 'Belge Özeti',
  'doc_ai_section_recommendations': 'Kişisel Öneriler',
  'doc_ai_summary_period': 'Ekstre Dönemi',
  'doc_ai_summary_last_payment': 'Son Ödeme',
  'doc_ai_summary_next_payment': 'Gelecek Son Ödeme',
  'doc_ai_summary_highlights': 'Öne çıkanlar',
  'doc_detail_ai_analysis': '✨ AI Analizi',
  'doc_detail_insights_title': 'Öne Çıkan Tespitler',
  'doc_detail_top_expense': 'En Büyük Harcama',
  'doc_detail_total_transactions': 'Toplam İşlem',
  'doc_detail_savings_potential': 'Tasarruf Potansiyeli',
  'doc_detail_no_expense': 'Gider işlemi yok',
  'doc_detail_tab_transactions': 'İşlemler',
  'doc_detail_tab_analysis': 'Analiz',
  'doc_detail_tab_recommendations': 'AI Önerileri',
  'doc_tab_transactions': 'İşlemler',
  'doc_tab_analysis': 'Analiz',
  'doc_tab_summary': 'Özet',
  'doc_tab_ai': 'AI',
  'doc_tab_installments': 'Taksitler',
  'doc_installments_empty': 'Bu belgede taksitli işlem bulunmuyor.',
  'doc_installments_monthly': 'Bu Ay',
  'doc_installments_remaining_total': 'Kalan Toplam',
  'doc_installments_count': 'Ürün Sayısı',
  'doc_installments_this_month': 'Bu ay',
  'doc_installments_paid': 'Ödenen',
  'doc_installments_left_count': 'Kalan',
  'doc_installments_installment': 'taksit',
  'doc_installments_remaining_amount': 'Kalan Tutar',
  'doc_detail_gross_expense': 'Brüt Harcama',
  'doc_detail_min_payment': 'Asgari Ödeme',
  'doc_detail_payment_due': 'Son Ödeme',
  'doc_grouped_view': 'Gruplu',
  'doc_list_view': 'Liste',
  'doc_carryover_label': 'Önceki Dönem Alacağı',
  'doc_net_debt_label': 'Net Dönem Borcu',
  'doc_debt_calc_title': '💳 Borç Kapatma Planı',
  'doc_debt_calc_current_debt': 'Güncel Borç',
  'doc_debt_calc_min_payment': 'Asgari Ödeme',
  'doc_debt_calc_min_scenario': 'Sadece asgari öderseniz: @months ay',
  'doc_debt_calc_min_detail': 'Toplam ödeme @total · Faiz yükü @interest',
  'doc_debt_calc_full_scenario': 'Tamamını şimdi öderseniz',
  'doc_debt_calc_full_detail': '@savings faiz ödemekten kurtulursunuz 🎉',
  'doc_installments_title': 'Devam Eden Taksitler',
  'doc_future_period_title': 'Gelecek Dönem',
  'doc_next_statement': 'Gelecek Hesap Kesim',
  'doc_next_payment_due': 'Gelecek Son Ödeme',
  'doc_detail_recurring_title': 'Tekrar Eden Ödemeler',
  'doc_detail_recurring_empty': 'Tekrarlayan gider tespit edilmedi.',
  'doc_detail_recurring_count': '@count kez',
  'doc_detail_ai_rec_idle_title': 'Kişisel AI önerileri',
  'doc_detail_ai_rec_fetch': 'Önerileri Getir',
  'doc_detail_ai_rec_loading': 'AI analiz ediyor...',
  'doc_detail_ai_rec_error':
      'Öneriler alınamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.',
  'doc_detail_ai_rec_retry': 'Tekrar Dene',
  'doc_detail_transactions_title': 'İşlemler',
  'doc_detail_transactions_by_category': 'Harcamalar (Kategoriye Göre)',
  'doc_detail_transactions_empty': 'İşlem bulunamadı.',
  'doc_detail_recommendations_empty': 'Henüz öneri yok',
  'doc_rec_priority_high': 'Yüksek',
  'doc_rec_priority_medium': 'Orta',
  'doc_rec_priority_low': 'Düşük',
  'doc_rec_overspend_title': 'Harcamalar geliri aşıyor',
  'doc_rec_overspend_body':
      'Bu dönemde giderleriniz gelirinizin üzerinde. İsteğe bağlı harcamaları gözden geçirmenizi öneririz.',
  'doc_rec_top_expense_title': 'En büyük harcama: @merchant',
  'doc_rec_top_expense_body':
      'Tek seferde @amount TL tutarındaki bu harcama bütçenizi en çok etkileyen kalemdir.',
  'doc_rec_savings_title': 'Tasarruf alanı var',
  'doc_rec_savings_body':
      'Gelir-gider farkınız pozitif. Fazla bakiyeyi birikim veya borç ödemesine yönlendirebilirsiniz.',
  'doc_rec_summary_title': 'AI değerlendirmesi',
  'doc_detail_not_found': 'Belge analizi bulunamadı. Lütfen PDF\'i yeniden yükleyin.',
  'doc_preview_unavailable':
      'PDF önizlemesi kullanılamıyor. Belgeyi yeniden yükleyin.',
  'doc_analysis_incomplete':
      'Bu belgenin AI analizi eksik veya başarısız. PDF kayıtlıysa yeniden analiz edin.',
  'doc_reanalyze_action': 'Yeniden analiz et',
  'doc_reanalyze_success_title': 'Analiz tamamlandı',
  'doc_reanalyze_success': 'Belge verileri güncellendi.',

  // Documents tab
  'documents_tab_title': 'Belgelerim',
  'documents_tab_subtitle': 'PDF ekstrelerinizi yükleyin ve geçmiş yüklemelerinizi yönetin.',

  // Analysis tab
  'analysis_select_document':
      'Bir belgeye dokunun; görüntüleme veya AI analizi seçin.',
  'analysis_empty': 'Henüz analiz edilecek belge yok. Önce bir PDF yükleyin.',
  'analysis_action_title': 'Ne yapmak istersiniz?',
  'analysis_open_ai': 'AI Analizi',
  'analysis_open_pdf': 'Belgeyi Görüntüle',

  // Aggregate
  'aggregate_title': 'Tüm Dönemler',
  'aggregate_grand_total': 'Genel Özet',
  'aggregate_total_expense': 'Toplam Harcama',
  'aggregate_total_income': 'Toplam Gelir',
  'aggregate_total_debt': 'Toplam KK Borcu',
  'aggregate_doc_count': 'Belge',
  'aggregate_monthly_chart': 'Aylık Harcama Trendi',
  'aggregate_top_categories': 'Kategori Dağılımı (Tüm Dönemler)',
  'aggregate_ai_insight': 'AI Trend Analizi',
  'aggregate_ai_load': 'Trend Analizini Getir',
  'aggregate_ai_retry': 'Tekrar Dene',
  'aggregate_empty':
      'Henüz yüklenmiş belge yok.\nEkstrenizi yükleyin, aylık trendlerinizi görün.',
};
